---
resources:
  - name: codebase
    type: git
    icon: github-circle
    source:
      uri: https://github.com/mavericks-consulting/ci-cd-workshop-demo.git

jobs:
  - name: test
    public: true
    plan:
      - get: codebase
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "8" }
          inputs:
            - name: codebase
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd codebase
                npm install
                npm test
